// <auto-generated />
using BookManagerAppMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagerAppMVC.Migrations
{
    [DbContext(typeof(BookManagerAppMVCContext))]
    [Migration("20240802022359_RentalHistory")]
    partial class RentalHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagerAppMVC.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentalHistoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookManagerAppMVC.Models.RentalHistory", b =>
                {
                    b.Property<int>("RentalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalHistoryId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("RentDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RentUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RentalHistoryId");

                    b.HasIndex("BookId");

                    b.ToTable("RentalHistory");
                });

            modelBuilder.Entity("BookManagerAppMVC.Models.RentalHistory", b =>
                {
                    b.HasOne("BookManagerAppMVC.Models.Book", "Book")
                        .WithMany("RentalHistorys")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookManagerAppMVC.Models.Book", b =>
                {
                    b.Navigation("RentalHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
